### ISSUE TITLE
Performance tests fail when running with Tag name.

### ISSUE THREAD

**Issue by whitingjr** [jbosstm/performance#175]
The Performance comparison script jenkins.sh fails. When setting a Tag name for the `NARAYANA_BRANCH` parameter and the project has been built already 
NARAYANA_BRANCH=7.0.0.Final
BUILD_NARAYANA=n

failing when `performance/scripts/hudson/jenkins.sh` [line 44](https://github.com/jbosstm/performance/blob/7.0.0.Final/scripts/hudson/jenkins.sh#L44) is executed. 

The error seen is 

```
fatal: ambiguous argument 'origin/7.0.0.Final': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
What I would like to see is the script be adaptable to support running with a Tag. So that project releases can be performance tested.

**Comment by marcosgopen** [comment]
As described in the [PR](https://github.com/jbosstm/performance/pull/176) you have to make sure that NARAYANA_BRANCH is present in your NARAYANA_REPO (default is jbosstm).
